# Generated by Django 2.2.6 on 2021-03-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=250)),
                ('pin_code', models.CharField(max_length=6)),
                ('available_from', models.DateField()),
                ('available_till', models.DateField(blank=True, null=True)),
                ('critical_level', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('book_from', models.DateField()),
                ('book_till', models.DateField()),
                ('bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupant', to='beds.Bed')),
            ],
        ),
    ]
